[package]
name = "lumberstack"
version = "0.1.2"
edition = "2021"
authors = [ "archae0pteryx <ryan@sudormrf.me>" ]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "3.0", features = ["derive"] }
exitcode = "1.1.2"
indicatif = "0.17.0"
handlebars = "4.3.3"
serde_json = "1.0"
chrono = "0.4.0"
walkdir = "2.3"
clap-verbosity-flag = "1.0.1"
env_logger = "0.9.0"
log = "0.4.17"
termcolor = "1.1.3"
cmd_lib = "1.3.0"
serde = { version = "1.0.144", features = ["derive"] }
question = "0.2.2"
rand = "0.8.5"
strum = { version = "0.24", features = ["derive"] }
