[package]
name = "lumberstack"
version = "0.1.0-beta.1"
edition = "2021"
authors = [ "archae0pteryx <ryan@sudormrf.me>" ]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "3.0", features = ["derive"] }
exitcode = "1.1.2"
indicatif = "0.17.0"
handlebars = "4.3.3"
serde_json = "1.0"
clap-verbosity-flag = "1.0.1"
env_logger = "0.9.0"
log = "0.4.17"
termcolor = "1.1.3"
serde = { version = "1.0.144", features = ["derive"] }
fs_extra = "1.2.0"
