- hosts: localhost
  become: yes
  become_user: '{{ lookup("env","USER") }}'
  gather_facts: false
  tasks:
  - name: Register template dir
    stat:
      path: tmp/templates
    register: tmp_templates
    tags:
    - init
  - name: Clone template repo
    git:
      repo: https://github.com/codingzeal/redwood-template-app
      dest: tmp/templates
      version: v0.0.4
    when: not tmp_templates.stat.exists
    tags:
    - init
  - name: Exclude dirs from search
    find:
      paths: tmp
      file_type: directory
      excludes:
      - .git
      - node_modules
      - .vscode
      recurse: yes
      hidden: yes
    register: filtered_dirs
    tags:
    - init
  - set_fact:
      dirs: '{{ filtered_dirs | json_query("files[*].path") }}'
    tags:
    - init
  - name: Gather all template paths
    find:
      paths: '{{ dirs }}'
      file_type: file
      recurse: no
      hidden: 'true'
      contains: (\/\/|\/\/\*|#|\<!--) template!?.*
    register: found_templates
    tags:
    - init
  - set_fact:
      template_paths: '{{ found_templates | json_query("files[*].path") }}'
    tags:
    - init
  - name: Write template map
    copy:
      dest: tmp/template_map.txt
      content: '{{ template_paths }}'
    tags:
    - init
