- hosts: 127.0.0.1
  connection: local
  gather_facts: true
  tasks:
  - name: Register template dir
    stat: {}
    register: tmp_templates
  - name: Clone template repo
    git:
      repo: ''
      dest: ''
    when: not tmp_templates.stat.exists
  - name: Exclude dirs from search
    find:
      file_type: directory
      excludes:
      - .git
      - node_modules
      - .vscode
      recurse: no
    register: filtered_dirs
  - set_fact:
      dirs: '{{ filtered_dirs | json_query("files[*].path") }}'
  - name: Gather all template paths
    find:
      paths: '{{ dirs }}'
      file_type: file
      recurse: yes
      hidden: 'true'
      contains: (\/\*|#|\<!--) template!?.*
    register: found_templates
  - set_fact:
      template_paths: '{{ found_templates | json_query("files[*].path") }}'
  - name: Write template map
    copy:
      dest: /template_map.txt
      content: '{{ template_paths  }}'
